source 'https://rubygems.org'

#gem 'gsl', :git => 'git://github.com/whistlerbrk/rb-gsl.git'
gem 'sinatra'
gem 'thin'
gem 'nokogiri'
gem 'feedzirra', '0.7.1'
gem 'similarity'
gem 'mongo'
gem 'slim'
gem 'bson'
gem 'bson_ext'
gem 'mongo_mapper'
gem 'mongoid'
gem 'mongoid_search'
gem 'haml'
gem 'data_mapper'
gem 'sqlite3'
gem 'dm-sqlite-adapter'
gem 'tf-idf-similarity'
